export const RECORD_WXINFO = 'RECORD_WXINFO';

export const SET_BOTTOMTABHEIGHT = 'SET_BOTTOMTABHEIGHT';

export const SET_CURRENTINDEX = 'SET_CURRENTINDEX';

export const HIDDEN_FOOT = 'HIDDEN_FOOT';